import os

replacements = {
    # core/env_setup.py
    "Ignorar pip en versión compilada (.exe)": "Ignorar pip en versión compilada (.exe)",
    "Analizar hardware": "Analizar hardware",
    "Refinar detección de NVIDIA con CUDA": "Refinar detección de NVIDIA con CUDA",
    "Confirmar existencia de nvcc o CUDA_PATH": "Confirmar existencia de nvcc o CUDA_PATH",
    "Verificar paquetes instalados": "Verificar paquetes instalados",
    "Prevenir conflictos (CPU instalado junto a DML anula aceleración)": "Prevenir conflictos (CPU instalado junto a DML anula aceleración)",
    "Limpiar paquetes superpuestos preventivamente": "Limpiar paquetes superpuestos preventivamente",
    "Instalar limpiamente el paquete objetivo": "Instalar limpiamente el paquete objetivo",

    # core/generative.py
    "Preparar imagen para img2img": "Preparar imagen para img2img",
    "Ejecutar redimensionamiento optimizando área total (Max 262144 píxeles)": "Ejecutar redimensionamiento optimizando área total (Max 262144 píxeles)",
    "Asegurar dimensiones múltiplo de 8 para SD": "Asegurar dimensiones múltiplo de 8 para SD",
    "Cargar modelo base": "Cargar modelo base",
    "Forzar float32 para prevenir imágenes negras (NaNs) en GTX 16xx": "Forzar float32 para prevenir imágenes negras (NaNs) en GTX 16xx",
    "Optimizar cálculos para reducir consumo VRAM": "Optimizar cálculos para reducir consumo VRAM",
    "Aplicar xformers si está disponible (previene NaNs en GTX 16xx)": "Aplicar xformers si está disponible (previene NaNs en GTX 16xx)",
    "Cargar LoRA previo a CPU OFFLOAD": "Cargar LoRA previo a CPU OFFLOAD",
    "Forzar dtype correcto en módulos LoRA inyectados": "Forzar dtype correcto en módulos LoRA inyectados",
    "Descargar componentes secuencialmente (vital para 4GB VRAM)": "Descargar componentes secuencialmente (vital para 4GB VRAM)",
    "Generar inferencia": "Generar inferencia",
    "Forzar Negative Prompt en modelos anime/arte": "Forzar Negative Prompt en modelos anime/arte",
    "Inyectar semilla única por iteración": "Inyectar semilla única por iteración",
    "Configurar parámetros comunes": "Configurar parámetros comunes",
    "Inyectar condicionalmente": "Inyectar condicionalmente",
    "Calcular progreso proporcional": "Calcular progreso proporcional",
    "Reducir imagen preventivamente para Moondream": "Reducir imagen preventivamente para Moondream",

    # core/threads.py
    "Configurar ejecución silenciosa (previene falsos AV y parpadeos)": "Configurar ejecución silenciosa (previene falsos AV y parpadeos)",
    "Probar nvidia-smi para NVIDIA": "Probar nvidia-smi para NVIDIA",
    "Utilizar fallback WMIC para AMD/Intel": "Utilizar fallback WMIC para AMD/Intel",
    "Leer segunda línea válida de output WMIC": "Leer segunda línea válida de output WMIC",
    "Retornar None si falla la detección": "Retornar None si falla la detección",
    "Manejar fallo en detección VRAM": "Manejar fallo en detección VRAM",
    "Registrar VRAM detectada": "Registrar VRAM detectada",
    "Liberar VRAM de modelos previos": "Liberar VRAM de modelos previos",
    "Evitar fallback silencioso de ONNX a CPU": "Evitar fallback silencioso de ONNX a CPU",
    "Detectar descarte de DirectML por ONNX": "Detectar descarte de DirectML por ONNX",
    "Bloquear ejecución en CPU por tiempos extremos": "Bloquear ejecución en CPU por tiempos extremos",
    "Evitar duplicar colores": "Evitar duplicar colores",
    "Retornar tensor crudo para SAM": "Retornar tensor crudo para SAM",
    "Purgar caché para liberar VRAM tras fallo crítico": "Purgar caché para liberar VRAM tras fallo crítico",
    "Aplicar auto-cast dinámico según modelo": "Aplicar auto-cast dinámico según modelo",
    "Reconvertir salida a FP32 para OpenCV": "Reconvertir salida a FP32 para OpenCV",
    "Normalizar ruta previniendo errores de caracteres especiales": "Normalizar ruta previniendo errores de caracteres especiales",
    "Inspeccionar dimensiones del modelo": "Inspeccionar dimensiones del modelo",
    "Determinar tamaño óptimo": "Determinar tamaño óptimo",
    "Respetar resolución exigida por ONNX": "Respetar resolución exigida por ONNX",
    "Aplicar optimización dinámica de VRAM": "Aplicar optimización dinámica de VRAM",
    "Ejecutar redimensionamiento a objetivo": "Ejecutar redimensionamiento a objetivo",
    "Analizar si el error es de memoria": "Analizar si el error es de memoria",
    "Detectar códigos OOM en DML (8007000E)": "Detectar códigos OOM en DML (8007000E)",
    "Fallar controladamente si el modelo es rígido": "Fallar controladamente si el modelo es rígido",
    "Lanzar error formateado": "Lanzar error formateado",
    "Reintentar con mitad de tamaño si es dinámico": "Reintentar con mitad de tamaño si es dinámico",
    "Lanzar error general limpio": "Lanzar error general limpio",
    "Fijar resolución a 518x518 para MoGe ViTS": "Fijar resolución a 518x518 para MoGe ViTS",
    "Aplicar normalización ImageNet": "Aplicar normalización ImageNet",
    "Calcular input_tokens para patch 14x14": "Calcular input_tokens para patch 14x14",
    "Buscar dinámicamente el output 'normal'": "Buscar dinámicamente el output 'normal'",
    "Transponer a (H, W, 3) por seguridad": "Transponer a (H, W, 3) por seguridad",
    "Convertir de OpenCV a Tangent Space (OpenGL)": "Convertir de OpenCV a Tangent Space (OpenGL)",
    "Escalar a [0, 255]": "Escalar a [0, 255]",
    "Restaurar resolución original": "Restaurar resolución original",
    "Restaurar canal Alpha": "Restaurar canal Alpha",
    "Ejecutar redimensionamiento a 1024x1024 para MobileSAM": "Ejecutar redimensionamiento a 1024x1024 para MobileSAM",
    "Extraer escala desde nombre de archivo": "Extraer escala desde nombre de archivo",
    "Detectar CodeFormer (requiere normalización [-1, 1])": "Detectar CodeFormer (requiere normalización [-1, 1])",
    "Inspeccionar forma de entrada": "Inspeccionar forma de entrada",
    "Detectar dimensiones rígidas y batch": "Detectar dimensiones rígidas y batch",
    "Manejar inp_shape con tipos mixtos (int, str, None)": "Manejar inp_shape con tipos mixtos (int, str, None)",
    "Confirmar dimensiones fijas": "Confirmar dimensiones fijas",
    "Aplicar forzados tras fallback": "Aplicar forzados tras fallback",
    "Usar batch size fijo": "Usar batch size fijo",
    "Configurar mosaico adaptativo": "Configurar mosaico adaptativo",
    "Respetar tamaño exigido": "Respetar tamaño exigido",
    "Forzar tamaño estándar para modelos pseudo-dinámicos": "Forzar tamaño estándar para modelos pseudo-dinámicos",
    "Calcular avance real (tamaño menos overlap)": "Calcular avance real (tamaño menos overlap)",
    "Inyectar tamaño de tensor en fixed_h/w": "Inyectar tamaño de tensor en fixed_h/w",
    "Forzar relleno exacto de mosaicos": "Forzar relleno exacto de mosaicos",
    "Recopilar tiles": "Recopilar tiles",
    "Asegurar múltiplos de 64 para modelos avanzados": "Asegurar múltiplos de 64 para modelos avanzados",
    "Cumplir requisitos de atención/downsampling": "Cumplir requisitos de atención/downsampling",
    "Formatear a (3, H, W) float32 RGB": "Formatear a (3, H, W) float32 RGB",
    "Procesar lotes con tamaño rígido": "Procesar lotes con tamaño rígido",
    "Rellenar batch rígido con copias": "Rellenar batch rígido con copias",
    "Apilar tensores en dimensión 0": "Apilar tensores en dimensión 0",
    "Escribir salida procesada en imagen final": "Escribir salida procesada en imagen final",
    "Detectar OOM": "Detectar OOM",
    "Intentar primer fallback": "Intentar primer fallback",
    "Lanzar error claro si falla el fallback": "Lanzar error claro si falla el fallback",
    "Detectar errores de shape, \"incompatible dimensions\" o fallos de parámetros de DirectML (80070057)": "Detectar errores de dimensiones o fallo DirectML",
    "Reintentar en modo ultra seguro (512x512, batch 1)": "Reintentar en modo ultra seguro (512x512, batch 1)",
    "Mostrar error técnico original": "Mostrar error técnico original",
    "Restaurar canal alpha escalado": "Restaurar canal alpha escalado",
    "Emitir lotes de descodificación en bloque": "Emitir lotes de descodificación en bloque",
    "Decodificar imágenes en paralelo multicore": "Decodificar imágenes en paralelo multicore",
    "Garantizar retorno secuencial con executor.map": "Garantizar retorno secuencial con executor.map",
    "Emitir remanente del buffer": "Emitir remanente del buffer",

    # editor/canvas_items.py
    "Aplicar fondo oscuro": "Aplicar fondo oscuro",
    "Dibujar tiradores": "Dibujar tiradores",
    "Dibujar esquinas": "Dibujar esquinas",
    "Dibujar centro": "Dibujar centro",
    "Ejecutar redimensionamiento": "Ejecutar redimensionamiento",

    # editor/image_tab.py
    "Definir grupos lógicos": "Definir grupos lógicos",
    "Crear contenedor STACK para visor": "Crear contenedor STACK para visor",
    "Montar visor al fondo": "Montar visor al fondo",
    "Montar panel flotante superior izquierdo": "Montar panel flotante superior izquierdo",
    "Añadir paneles al layout superpuesto": "Añadir paneles al layout superpuesto",
    "Ensamblar UI": "Ensamblar UI",
    "Añadir scroll a contenedor paleta": "Añadir scroll a contenedor paleta",
    "Mantener estado al cerrar flyout de paleta": "Mantener estado al cerrar flyout de paleta",
    "Preservar visibilidad y liberar ratón": "Preservar visibilidad y liberar ratón",
    "Extraer array NumPy para BLIP": "Extraer array NumPy para BLIP",
    "Anular comandos paramétricos pendientes": "Anular comandos paramétricos pendientes",
    "Hornear imagen por pipeline a máxima resolución": "Hornear imagen por pipeline a máxima resolución",
    "Finalizar acción Qt": "Finalizar acción Qt",
    "Abortar comando historial": "Abortar comando historial",
    "Mapear rect de escena a rect de pixmap": "Mapear rect de escena a rect de pixmap",
    "Intersectar coordenadas para no desbordar imagen": "Intersectar coordenadas para no desbordar imagen",
    "Ignorar clics diminutos accidentales": "Ignorar clics diminutos accidentales",
    "Recortar imagen horneada": "Recortar imagen horneada",
    "Resetear parámetros y usar recorte como base": "Resetear parámetros y usar recorte como base",
    "Asegurar memoria contigua modificable para OpenCV": "Asegurar memoria contigua modificable para OpenCV",
    "Mapear tolerancia a rango 0-255": "Mapear tolerancia a rango 0-255",
    "Añadir holgura escalada a tolerancia": "Añadir holgura escalada a tolerancia",
    "Ampliar máscara +2 píxeles para floodFill": "Ampliar máscara +2 píxeles para floodFill",
    "Usar floodFill en FLOODFILL_MASK_ONLY para preservar color": "Usar floodFill en FLOODFILL_MASK_ONLY para preservar color",
    "Recortar borde auxiliar de máscara": "Recortar borde auxiliar de máscara",
    "1. Dilatar ligeramente la máscara para comerse el \"halo\" o \"fleco\" del color": "Dilatar máscara para eliminar halos",
    "Suavizar bordes con desenfoque Gaussiano": "Suavizar bordes con desenfoque Gaussiano",
    "Aplicar transparencia con canal Alfa": "Aplicar transparencia con canal Alfa",
    "Preservar zoom evitando resetear parámetros": "Preservar zoom evitando resetear parámetros",
    "Convertir QImage de forma asíncrona segura": "Convertir QImage de forma asíncrona segura",
    "Limpiar asíncronamente recursos": "Limpiar asíncronamente recursos",
    "Extraer imagen del visor en formato RGB": "Extraer imagen del visor en formato RGB",
    "Respetar padding de 4 bytes por línea en QImage": "Respetar padding de 4 bytes por línea en QImage",
    "Eliminar padding y formatear a (H, W, 3)": "Eliminar padding y formatear a (H, W, 3)",
    "Mostrar diálogo confirmación IA": "Mostrar diálogo confirmación IA",
    "Validar modo edición activo": "Validar modo edición activo",
    "Restaurar UI con nueva imagen principal": "Restaurar UI con nueva imagen principal",
    "Actualizar título pestaña": "Actualizar título pestaña",
    "Diferenciar entre falta hardware o error técnico": "Diferenciar entre falta hardware o error técnico",
    "Lanzar advertencia hardware": "Lanzar advertencia hardware",
    "Lanzar error técnico": "Lanzar error técnico",
    "Preservar referencias vivas en scope Python": "Preservar referencias vivas en scope Python",
    "Delegar destrucción a bucle de eventos (deleteLater)": "Delegar destrucción a bucle de eventos (deleteLater)",
    "Permitir sobrescritura en siguiente iteración IA": "Permitir sobrescritura en siguiente iteración IA",
    "Escalar marcador circular al 2.5%": "Escalar marcador circular al 2.5%",
    "Situar marcador en coordenadas reales": "Situar marcador en coordenadas reales",
    "Actualizar sliders transformaciones": "Actualizar sliders transformaciones",
    "Actualizar spinboxes lienzo": "Actualizar spinboxes lienzo",
    "Actualizar fondo lienzo": "Actualizar fondo lienzo",
    "Castear a QColor para asegurar método .name()": "Castear a QColor para asegurar método .name()",
    "Implementar timer para prevenir crashes de animación": "Implementar timer para prevenir crashes de animación",
    "Renderizar contenido a resolución nativa": "Renderizar contenido a resolución nativa",
    "Invocar procesamiento sobre imagen original pura": "Invocar procesamiento sobre imagen original pura",
    "Mapear rango numérico a factor flotante": "Mapear rango numérico a factor flotante",
    "Navegar imágenes galería": "Navegar imágenes galería",

    # tools/ai_tool.py
    "Configurar cabecera tarjeta": "Configurar cabecera tarjeta",
    "Configurar cuerpo grid tarjeta": "Configurar cuerpo grid tarjeta",
    "Insertar caja descriptiva izquierda": "Insertar caja descriptiva izquierda",
    "Insertar InfoBoxes derecha": "Insertar InfoBoxes derecha",
    "Configurar footer tarjeta": "Configurar footer tarjeta",
    "Aplicar estilo CSS dinámico": "Aplicar estilo CSS dinámico",
    "Ordenar catálogo según VRAM (ascendente)": "Ordenar catálogo según VRAM (ascendente)",
    "Filtrar por tipo artístico": "Filtrar por tipo artístico",
    "Filtrar por requisitos técnicos VRAM": "Filtrar por requisitos técnicos VRAM",

    # tools/factory.py
    "Asegurar compatibilidad paths PyInstaller (_internal)": "Asegurar compatibilidad paths PyInstaller (_internal)",
    "Utilizar caché global previniendo duplicidades memoria": "Utilizar caché global previniendo duplicidades memoria",
    "Generar token único derivado de estilo": "Generar token único derivado de estilo",
    "Prevenir colisión métodos Enum Qt": "Prevenir colisión métodos Enum Qt",
    "Aplicar rotación CSS": "Aplicar rotación CSS",
    "Aplicar tintado (SourceIn) si corresponde": "Aplicar tintado (SourceIn) si corresponde",
    "Almacenar pixmap en caché": "Almacenar pixmap en caché",

    # tools/mirror_tool.py
    "Simplificar márgenes y layout": "Simplificar márgenes y layout",
    "Definir botones de UI declarativamente": "Definir botones de UI declarativamente",

    # tools/sam_tool.py
    "Instanciar ONNX Decoder": "Instanciar ONNX Decoder",
    "Transformar puntos origen a grilla 1024": "Transformar puntos origen a grilla 1024",
    "Definir inputs de modelo estrictos": "Definir inputs de modelo estrictos",
    "Ejecutar redimensionamiento al original": "Restaurar resolución nativa",
    "Binarizar máscara (umbral > 0)": "Binarizar máscara (umbral > 0)",
    "Generar Overlay QPixmap (Verde Alfa)": "Generar Overlay QPixmap (Verde Alfa)",
    "Transferir Alpha de máscara a Alpha objetivo": "Transferir Alpha de máscara a Alpha objetivo",

    # ui/gallery_view.py
    "Renderizar pixmap directamente (ya pre-escalado)": "Renderizar pixmap directamente (ya pre-escalado)",
    "Calcular columnas adaptativas": "Calcular columnas adaptativas",
    "Calcular filas requeridas": "Calcular filas requeridas",
    "Calcular altura total necesaria del viewport": "Calcular altura total necesaria del viewport",

    # ui/gallery_window.py
    "Eliminar temporal de IA al cerrar pestaña": "Eliminar temporal de IA al cerrar pestaña",
    "Deshabilitar botones inicialmente": "Deshabilitar botones inicialmente",
    "Ensamblar lado izquierdo UI (Galería)": "Ensamblar lado izquierdo UI (Galería)",
    "Re-mezclar si opción es Azar": "Re-mezclar si opción es Azar",
    "Alternar ícono dinámico si es Azar": "Alternar ícono dinámico si es Azar",
    "Reevaluar archivo modificado (remover/añadir)": "Reevaluar archivo modificado (remover/añadir)",
    "Purgar variables liberando RAM": "Purgar variables liberando RAM",
    "Limitar actualización barra progreso": "Limitar actualización barra progreso",
    "Actualizar métricas cabecera": "Actualizar métricas cabecera",
    "Ordenar items lógicamente": "Ordenar items lógicamente",
    "Agrupar y repintar DOM optimizado": "Agrupar y repintar DOM optimizado",
    "Reutilizar bloque único (Sin agrupaciones)": "Reutilizar bloque único (Sin agrupaciones)",
    "Limpiar layout en transición grupos -> lista": "Limpiar layout en transición grupos -> lista",
    "Reconstruir layout completo por agrupaciones": "Reconstruir layout completo por agrupaciones",
    "Habilitar panel herramientas solo para selección única": "Habilitar panel herramientas solo para selección única",
    "Mostrar vista previa para única imagen": "Mostrar vista previa para única imagen",
    "Ocultar panel previsualización por selección múltiple": "Ocultar panel previsualización por selección múltiple",
    "Verificar lógica selección externa": "Verificar lógica selección externa",
    "Forzar refresco visual contingente": "Forzar refresco visual contingente",
    "Localizar índice absoluto imagen actual": "Localizar índice absoluto imagen actual",
    "Asegurar no desbordar índices": "Asegurar no desbordar índices",
    "Cerrar pestaña previa y liberar memoria": "Cerrar pestaña previa y liberar memoria",
    "Instanciar nueva pestaña sobre misma vista": "Instanciar nueva pestaña sobre misma vista",

    # ui/widgets.py
    "Asignar paleta colores dinámicos": "Asignar paleta colores dinámicos",
    "Calcular click proporcional eje Y": "Calcular click proporcional eje Y",
    "Invertir eje Y compensando origen Qt": "Invertir eje Y compensando origen Qt",
    "Instanciar QPen sombra": "Instanciar QPen sombra",
    "Instanciar QPen núcleo blanco": "Instanciar QPen núcleo blanco",
    "Renderizar checkerboard alpha": "Renderizar checkerboard alpha",
    "Dibujar stroke negro base": "Dibujar stroke negro base",
    "Dibujar stroke blanco interno": "Dibujar stroke blanco interno",
    "Preservar flag drag_mode (Magic Eraser)": "Preservar flag drag_mode (Magic Eraser)",
    "Ignorar eventos absorbidos por CropOverlayItem": "Ignorar eventos absorbidos por CropOverlayItem",
    "Propagar eventos secundarios QGraphicsItem": "Propagar eventos secundarios QGraphicsItem",
    "Habilitar Panning al deseleccionar click fuera": "Habilitar Panning al deseleccionar click fuera",
    "Generar pattern image base (32x32)": "Generar pattern image base (32x32)",
    "Rellenar viewport con Brush checkerboard": "Rellenar viewport con Brush checkerboard",
    "Calcular zoom delta tentativo": "Calcular zoom delta tentativo",
    "Restringir zoom entre límites absolutos (0.5x -> 40x)": "Restringir zoom entre límites absolutos (0.5x -> 40x)",
    "Determinar delta relacional vs factor base": "Determinar delta relacional vs factor base",
    "Emitir Scale Matrix Transformation": "Emitir Scale Matrix Transformation",

    # studio_logger.py
    "Compilar Regex global optimizando CPU": "Compilar Regex global optimizando CPU",
    "1. Determinar el \"Tag\" dinámico de forma robusta": "Extraer Tag contextual dinámico",
    "Asignar Tag genérico si falta decorador": "Asignar Tag genérico si falta decorador",
    "Inyectar códigos color ANSI CLI": "Inyectar códigos color ANSI CLI",
    "Limpiar strings ANSI para output texto plano": "Limpiar strings ANSI para output texto plano",
    "Formatear stack Traceback C++/Python": "Formatear stack Traceback C++/Python",
    "Alinear mensajes multilínea a padding header": "Alinear mensajes multilínea a padding header",
    "Instanciar Handler Console StdOut": "Instanciar Handler Console StdOut",
    "Instanciar Handler FileAudit plano": "Instanciar Handler FileAudit plano",
    "Abrir modo W purgando historial antiguo": "Abrir modo W purgando historial antiguo",
    "Enganchar FaultHandler capturando SEGFAULT C++": "Enganchar FaultHandler capturando SEGFAULT C++",
    "Preservar file handle GarbageCollector": "Preservar file handle GarbageCollector",
    "Volcar exc_info logueando stackframe fallido": "Volcar exc_info logueando stackframe fallido",
}

for root, _, files in os.walk('.'):
    if '.venv' in root or 'build' in root or 'dist' in root:
        continue
    for file in files:
        if file.endswith('.py'):
            filepath = os.path.join(root, file)
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()
            
            modified = False
            for old, new in replacements.items():
                if old in content:
                    content = content.replace(old, new)
                    modified = True
            
            if modified:
                with open(filepath, 'w', encoding='utf-8') as f:
                    f.write(content)
                print(f"Updated {filepath}")
print("Replacement script complete")
